name: apcconda312
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _anaconda_depends=2025.06
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiobotocore=2.24.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - alembic=1.16.5
  - altair=5.5.0
  - amqp=5.2.0
  - anaconda-catalogs=0.2.0
  - annotated-types=0.7.0
  - anyio=4.10.0
  - aom=3.5.0
  - appdirs=1.4.4
  - archspec=0.2.5
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - arrow-cpp=16.1.0
  - asgiref=3.9.1
  - astroid=3.3.11
  - astropy=7.1.0
  - astropy-base=7.1.0
  - astropy-iers-data=0.2025.8.25.0.36.58
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=4.0.3
  - atomicwrites=1.4.1
  - attrs=25.3.0
  - automat=25.4.16
  - autopep8=2.0.4
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.17
  - aws-c-http=0.7.0
  - aws-c-io=0.13.12
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - backrefs=5.8
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.5
  - billiard=4.2.1
  - binaryornot=0.4.4
  - black=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.5
  - bokeh=3.7.3
  - boltons=25.0.0
  - boost-cpp=1.85.0
  - boto3=1.39.11
  - botocore=1.39.11
  - bottleneck=1.5.0
  - bqplot=0.12.43
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.14.4
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - catalogue=2.0.10
  - celery=5.5.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=3.470
  - chardet=5.2.0
  - charls=2.2.0
  - charset-normalizer=3.4.3
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1.2
  - click-repl=0.3.0
  - cloudpathlib=0.21.1
  - cloudpickle=3.1.1
  - cmarkgfm=2024.11.20
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - conda=24.11.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.9.0
  - conda-pack=0.8.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - conda-repo-cli=1.0.173
  - confection=0.1.5
  - constantly=23.10.4
  - contourpy=1.3.3
  - cookiecutter=2.6.0
  - coverage=7.10.5
  - cpython=3.12.11
  - cryptography=45.0.6
  - cssselect=1.3.0
  - cuda-cccl_linux-64=13.0.50
  - cuda-cudart-dev_linux-64=13.0.48
  - cuda-cudart-static_linux-64=13.0.48
  - cuda-cudart_linux-64=13.0.48
  - cuda-nvrtc=13.0.48
  - cuda-version=13.0
  - cupy=13.6.0
  - cupy-core=13.6.0
  - curl=8.9.1
  - cycler=0.12.1
  - cymem=2.0.11
  - cyrus-sasl=2.1.28
  - cython-blis=1.3.0
  - cytoolz=1.0.1
  - dask=2025.7.0
  - dask-core=2025.7.0
  - dask-expr=2.0.0
  - dataclasses=0.8
  - datasets=2.2.1
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.16
  - decorator=5.2.1
  - deepdiff=8.6.0
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20241021
  - dill=0.4.0
  - distributed=2025.7.0
  - distro=1.9.0
  - django=5.2.5
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - duckdb=1.3.2
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - faker=37.6.0
  - fastrlock=0.8.3
  - filelock=3.19.1
  - fire=0.7.0
  - flake8=7.1.2
  - flask=3.1.2
  - flask-cors=6.0.1
  - fmt=9.1.0
  - fontconfig=2.14.2
  - fonttools=4.59.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozendict=2.4.6
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gast=0.6.0
  - gensim=4.3.3
  - gflags=2.2.2
  - ghp-import=2.1.0
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-api-core=2.25.1
  - google-api-python-client=2.179.0
  - google-auth=2.40.3
  - google-auth-httplib2=0.2.0
  - googleapis-common-protos=1.70.0
  - greenlet=3.2.4
  - griffe=1.13.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.13.0
  - hdf5=1.14.3
  - heapdict=1.0.1
  - hf-xet=1.1.8
  - holoviews=1.21.0
  - hpack=4.1.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httplib2=0.22.0
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - hvplot=0.12.0
  - hyperframe=6.1.0
  - hyperlink=21.0.0
  - icu=73.2
  - id=1.5.0
  - idna=3.10
  - imagecodecs=2023.1.23
  - imageio=2.37.0
  - imagesize=1.4.1
  - imbalanced-learn=0.14.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - incremental=24.7.2
  - inflection=0.5.1
  - iniconfig=2.0.0
  - intake=2.0.8
  - intel-openmp=2025.0.0
  - intervaltree=3.1.0
  - ipydatagrid=1.4.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - isort=6.0.1
  - itemadapter=0.12.1
  - itemloaders=1.3.2
  - itsdangerous=2.2.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.3.0
  - jedi=0.19.2
  - jeepney=0.9.0
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jpeg=9e
  - jplephem=2.23
  - jproperties=2.1.2
  - jq=1.8.1
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab-variableinspector=3.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - keyring=25.6.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - kombu=5.5.4
  - krb5=1.20.1
  - langchain=0.3.27
  - langchain-core=0.3.75
  - langchain-text-splitters=0.3.10
  - langcodes=3.4.1
  - langsmith=0.3.45
  - language-data=1.3.0
  - lazy-loader=0.4
  - lazy-object-proxy=1.12.0
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarchive=3.6.2
  - libavif=0.11.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=13.0.0.19
  - libcufft=12.0.0.15
  - libcups=2.4.2
  - libcurand=10.4.0.35
  - libcurl=8.9.1
  - libcusolver=12.0.3.29
  - libcusparse=12.6.2.49
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=15.1.0
  - libglib=2.80.2
  - libgomp=15.1.0
  - libgrpc=1.62.2
  - libhwloc=2.9.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblief=0.16.6
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnvjitlink=13.0.39
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.29
  - libspatialindex=2.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.4
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - llvm-openmp=20.1.8
  - llvmlite=0.43.0
  - locket=1.0.0
  - loguru=0.7.3
  - lxml=5.2.1
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.3.10
  - marisa-trie=1.2.1
  - markdown=3.8.2
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mbedtls=3.6.3.1
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - menuinst=2.3.1
  - mergedeep=1.3.4
  - mistune=3.1.3
  - mkdocs=1.6.1
  - mkdocs-autorefs=1.4.3
  - mkdocs-get-deps=0.2.0
  - mkdocs-material=9.6.18
  - mkdocs-material-extensions=1.3.1
  - mkdocstrings=0.30.0
  - mkdocstrings-python=1.18.0
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.10
  - mkl_random=1.2.8
  - more-itertools=10.7.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msal=1.33.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multipledispatch=0.6.0
  - multiprocess=0.70.18
  - munkres=1.1.4
  - murmurhash=1.0.13
  - mypy=1.17.1
  - mypy_extensions=1.1.0
  - mysql=5.7.24
  - mysql-common=8.3.0
  - mysql-connector-python=8.3.0
  - mysql-libs=8.3.0
  - narwhals=2.2.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nh3=0.3.0
  - nltk=3.9.1
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.100
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.9.0
  - oauth2client=4.1.3
  - office365-rest-python-client=2.6.2
  - oniguruma=6.9.10
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.2
  - opentelemetry-api=1.36.0
  - opentelemetry-instrumentation=0.57b0
  - opentelemetry-semantic-conventions=0.57b0
  - orc=2.0.1
  - orderly-set=5.5.0
  - orjson=3.11.3
  - overrides=7.7.0
  - packaging=25.0
  - paginate=0.5.7
  - pandas=2.3.2
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - panel=1.7.5
  - param=2.2.1
  - parsel=1.10.0
  - parso=0.8.5
  - partd=1.4.2
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=25.2
  - pkce=1.0.3
  - pkginfo=1.12.1.2
  - platformdirs=4.4.0
  - plotly=6.3.0
  - pluggy=1.6.0
  - ply=3.11
  - polars=1.32.3
  - polars-default=1.32.3
  - preshed=3.0.9
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - protego=0.5.0
  - proto-plus=1.26.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-lief=0.16.6
  - py-xgboost=3.0.4
  - py2vega=0.6.0
  - py4j=0.10.9.9
  - pyarrow=16.1.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=5
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pycryptodome=3.23.0
  - pyct=0.5.0
  - pycurl=7.45.3
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydeck=0.8.0
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.5
  - pyflakes=3.2.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylint=3.3.8
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pymdown-extensions=10.16.1
  - pyodbc=5.2.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pyspark=4.0.0
  - pytables=3.9.2
  - pytest=8.4.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-docx=1.2.0
  - python-dotenv=1.1.1
  - python-duckdb=1.3.2
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.11
  - python-json-logger=2.0.7
  - python-libarchive-c=5.3
  - python-lmdb=1.7.3
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytoolconfig=1.2.6
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pywin32=311
  - pyxdg=0.28
  - pyyaml=6.0.2
  - pyyaml-env-tag=1.1
  - pyzmq=27.0.2
  - qdarkstyle=3.2.3
  - qhull=2020.2
  - qstylizer=0.2.4
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.5.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.3
  - queuelib=1.8.0
  - rapidfuzz=3.14.0
  - re2=2022.04.01
  - readline=8.2
  - readme_renderer=44.0
  - redis-py=6.4.0
  - referencing=0.36.2
  - regex=2025.7.34
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - requests-file=2.1.0
  - requests-toolbelt=1.0.0
  - responses=0.18.0
  - rfc3339-validator=0.1.4
  - rfc3986=2.0.0
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - roman-numerals-py=3.1.0
  - rope=1.14.0
  - rpds-py=0.27.1
  - rsa=4.9.1
  - rstcheck=6.2.5
  - rstcheck-core=1.2.2
  - rtree=1.4.1
  - ruamel.yaml=0.18.15
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.17.21
  - s2n=1.3.31
  - s3fs=2025.7.0
  - s3transfer=0.13.1
  - safetensors=0.6.2
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.13.1
  - scrapy=2.13.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - secretstorage=3.3.3
  - semver=3.0.4
  - send2trash=1.8.3
  - service-identity=24.2.0
  - service_identity=24.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simplejson=3.20.1
  - sip=6.7.12
  - six=1.17.0
  - smart-open=7.3.0.post1
  - smart_open=7.3.0.post1
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - spacy=3.8.7
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sphinx=8.3.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.6
  - spyder-kernels=2.5.2
  - sqlalchemy=2.0.43
  - sqlite=3.46.0
  - sqlparse=0.5.3
  - srsly=2.5.1
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - streamlit=1.49.0
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tblib=3.1.0
  - tenacity=9.1.2
  - termcolor=3.1.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - thinc=8.3.6
  - threadpoolctl=3.6.0
  - three-merge=0.1.1
  - tifffile=2023.8.12
  - tinycss2=1.4.0
  - tk=8.6.14
  - tldextract=5.3.0
  - tokenizers=0.21.4
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - toolz=1.0.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - transformers=4.55.4
  - truststore=0.10.3
  - twine=6.1.0
  - twisted=25.5.0
  - typer=0.16.1
  - typer-slim=0.16.1
  - typer-slim-standard=0.16.1
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - ujson=5.11.0
  - uncompresspy=0.4.0
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - unixodbc=2.3.12
  - uri-template=1.3.0
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - versioneer=0.29
  - vine=5.1.0
  - w3lib=2.3.1
  - wasabi=1.1.3
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.3
  - wurlitzer=3.1.1
  - xarray=2025.8.0
  - xgboost=3.0.4
  - xlsxwriter=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xyzservices=2025.4.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.43.0
  - yarl=1.20.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=7.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - aiohttp-cors==0.8.1
      - astunparse==1.6.3
      - build==1.3.0
      - bytewax==0.21.1
      - click==7.1.2
      - colorclass==2.2.2
      - colorful==0.5.7
      - colorlog==6.9.0
      - compressed-rtf==1.0.7
      - confluent-kafka==2.11.1
      - croniter==6.0.0
      - dash==3.2.0
      - distlib==0.4.0
      - dnspython==2.7.0
      - easygui==0.98.3
      - ebcdic==1.1.1
      - elastic-transport==9.1.0
      - elasticsearch==9.1.0
      - email-validator==2.2.0
      - extract-msg==0.55.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - faust==1.10.4
      - flatbuffers==25.2.10
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - gunicorn==23.0.0
      - httptools==0.6.4
      - influxdb-client==1.49.0
      - kafka-python==1.4.7
      - keras==3.11.3
      - lark==1.1.9
      - libclang==18.1.1
      - ml-dtypes==0.5.3
      - mode==4.3.2
      - msoffcrypto-tool==5.4.2
      - namex==0.1.0
      - neo4j==5.28.2
      - neomodel==5.5.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - olefile==0.47
      - oletools==0.60.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-exporter-prometheus==0.57b0
      - opentelemetry-proto==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentracing==1.3.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - parsimonious==0.10.0
      - pcodedmp==1.2.6
      - protobuf==6.32.0
      - psycopg==3.2.9
      - psycopg-binary==3.2.9
      - psycopg-pool==3.2.6
      - py-spy==0.4.1
      - pymysql==1.1.2
      - pyproject-hooks==1.2.0
      - pyspnego==0.11.2
      - python-multipart==0.0.20
      - ray==2.48.0
      - reactivex==4.0.4
      - red-black-tree-mod==1.22
      - requests-ntlm==1.3.0
      - retrying==1.4.2
      - rich-toolkit==0.15.0
      - rignore==0.6.4
      - robinhood-aiokafka==1.1.6
      - rtfde==0.1.2.1
      - sentence-transformers==5.1.0
      - sentry-sdk==2.35.0
      - singlestoredb==1.15.2
      - sqlglot==27.8.0
      - sqlglotrs==0.6.1
      - sqlparams==6.2.0
      - starlette==0.47.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.20.0
      - terminaltables==3.1.10
      - textblob==0.19.0
      - tokenize-rt==6.2.0
      - torch==2.8.0
      - torchvision==0.23.0
      - triton==3.4.0
      - tzlocal==5.3.1
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - venusian==1.2.0
      - virtualenv==20.34.0
      - watchfiles==1.1.0
      - websockets==15.0.1
